import Link from "next/link"
import { requireAdmin } from "@/lib/admin-auth"
import { db } from "@/lib/db"

export const dynamic = "force-dynamic"

export default async function ServiceCampaignAnalyticsPage() {
  await requireAdmin()
  const [campaigns, events, discoveryEvents] = await Promise.all([
    db.serviceDiscoveryCampaign.findMany({ orderBy: [{ priority: "desc" }, { createdAt: "desc" }] }),
    db.serviceCampaignEvent.groupBy({ by: ["campaignId", "eventType"], _count: { _all: true }, _sum: { value: true } }),
    db.serviceDiscoveryEvent.groupBy({ by: ["eventType"], _count: { _all: true } }),
  ])
  const byCampaign = new Map<string, { impressions: number; clicks: number; conversions: number; revenue: number }>()
  for (const event of events) { const row = byCampaign.get(event.campaignId) ?? { impressions: 0, clicks: 0, conversions: 0, revenue: 0 }; if (event.eventType === "IMPRESSION") row.impressions += event._count._all; if (event.eventType === "CLICK") row.clicks += event._count._all; if (event.eventType === "CONVERSION") { row.conversions += event._count._all; row.revenue += Number(event._sum.value ?? 0) }; byCampaign.set(event.campaignId, row) }
  const totals = Array.from(byCampaign.values()).reduce((sum, item) => ({ impressions: sum.impressions + item.impressions, clicks: sum.clicks + item.clicks, conversions: sum.conversions + item.conversions, revenue: sum.revenue + item.revenue }), { impressions: 0, clicks: 0, conversions: 0, revenue: 0 })
  return <div className="mx-auto max-w-6xl space-y-6 pb-20"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-700">Service discovery</p><h1 className="mt-2 text-3xl font-bold text-foreground">Campaign Analytics</h1></div><Link href="/admin/service-campaigns" className="rounded-xl border border-border bg-card px-4 py-2 text-sm font-semibold text-foreground">Campaign Center</Link></div><div className="grid gap-4 md:grid-cols-4"><Metric label="Impressions" value={totals.impressions} /><Metric label="Clicks" value={totals.clicks} /><Metric label="Conversions" value={totals.conversions} /><Metric label="Tracked revenue" value={`$${totals.revenue.toFixed(2)}`} /></div><div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-4">Campaign</th><th className="px-5 py-4">Views</th><th className="px-5 py-4">Clicks</th><th className="px-5 py-4">CTR</th><th className="px-5 py-4">Conversions</th></tr></thead><tbody className="divide-y divide-border">{campaigns.map((campaign) => { const item = byCampaign.get(campaign.id) ?? { impressions: 0, clicks: 0, conversions: 0, revenue: 0 }; return <tr key={campaign.id}><td className="px-5 py-4"><p className="font-semibold text-foreground">{campaign.name}</p><p className="text-xs text-muted-foreground">{campaign.status}</p></td><td className="px-5 py-4">{item.impressions}</td><td className="px-5 py-4">{item.clicks}</td><td className="px-5 py-4">{item.impressions ? `${((item.clicks / item.impressions) * 100).toFixed(1)}%` : "0%"}</td><td className="px-5 py-4">{item.conversions}</td></tr> })}</tbody></table></div><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="font-bold text-foreground">Recommendation signals</h2><div className="mt-4 flex flex-wrap gap-3">{discoveryEvents.map((event) => <span key={event.eventType} className="rounded-full bg-muted px-3 py-2 text-sm text-muted-foreground">{event.eventType.replace("_", " ")}: <strong className="text-foreground">{event._count._all}</strong></span>)}</div></div></div>
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold text-foreground">{value}</p></div> }
