/**
 * lib/content/legal-blocks.ts
 * Abhibhideveloper legal drafts (Terms, Privacy, Refund/Delivery, Cookies,
 * Acceptable Use) exactly as provided in the content blueprint. Rendered
 * additively under each existing policy page. Placeholders in [brackets] are
 * intentionally preserved until the business supplies the details.
 */
import type { BlockSection } from "./brand-blocks"

export const TERMS_ADDENDUM: BlockSection[] = [
  { heading: "Terms and Conditions — Digital Marketplace & Services Draft", lead: "Last updated: [Insert publication date] — these clauses supplement the existing terms above and govern access to and use of our website, digital marketplace, products, subscriptions, software solutions, and technology services." },
  { heading: "1. Introduction", body: ["Welcome to Abhibhideveloper (\"Abhibhideveloper\", \"we\", \"us\", or \"our\"). These Terms and Conditions govern access to and use of our website, digital marketplace, products, subscriptions, software solutions, and technology services.", "By accessing our website, creating an account, purchasing a product, or engaging our services, you agree to the terms applicable to your activity. If you do not agree, please do not use the relevant service.", "These terms do not remove any rights that cannot legally be excluded or limited."] },
  { heading: "2. Business and Service Information", body: ["Abhibhideveloper offers or may offer digital products, AI-powered solutions, software, website and web application development, automation, subscriptions, deployment assistance, maintenance, and technical support.", "The specific services available at any time are those actually listed, offered, or agreed in writing. The terms of an individual order, product licence, subscription, or project agreement may supplement these general terms."] },
  { heading: "3. Eligibility and Account Responsibility", body: ["You must be legally capable of entering into a binding agreement to make a purchase or enter into a contract. If you act for a business or another person, you confirm that you are authorized to do so.", "You must provide accurate account and billing information, maintain the confidentiality of your login credentials, and notify us if you suspect unauthorized access.", "You are responsible for activity conducted through your account, subject to applicable law and circumstances outside your reasonable control."] },
  { heading: "4. Product Information and Availability", body: ["We aim to describe products, features, compatibility, pricing, limitations, and included services accurately.", "Digital products may have technical requirements, usage limits, dependencies, or restrictions. A product demonstration may not include all paid features or production capabilities.", "We may correct genuine errors and update products or listings. A material change affecting a confirmed order will be handled in accordance with the applicable agreement and law."] },
  { heading: "5. Orders, Quotations, and Project Scope", body: ["A quotation or proposal will identify the proposed work, price, relevant milestones, deliverables, and other conditions to the extent applicable.", "A custom project begins when the necessary agreement, approvals, and payment conditions have been satisfied.", "Work outside the agreed scope, additional features, third-party charges, migrations, or material changes may require a separate written quotation and approval.", "Estimated timelines depend on the agreed scope, customer cooperation, access to required information, and third-party dependencies. Any revised timeline should be communicated where reasonably practicable."] },
  { heading: "6. Pricing, Taxes, and Payments", body: ["Prices and billing intervals will be disclosed through the relevant listing, quotation, or checkout.", "Applicable taxes and additional charges will be presented or communicated as required by law.", "Payments must be made through the available authorized payment methods. An order is not treated as successfully paid solely because a payment attempt has been initiated. Payment status may be verified through the payment provider, settlement records, or another approved process.", "Where a payment is pending, duplicated, incorrectly recorded, reversed, or disputed, we may investigate the transaction and correct the corresponding account or billing record, subject to applicable law."] },
  { heading: "7. Digital Delivery and Activation", body: ["Delivery may involve a download, account entitlement, software activation, configuration, deployment, or another method stated in the product description or agreement.", "Activation may depend on payment verification, required customer information, technical compatibility, and third-party services.", "We will communicate material delivery issues where reasonably practicable and handle unresolved orders in accordance with the relevant terms and applicable law."] },
  { heading: "8. Subscriptions, Renewals, and Cancellation", body: ["Subscription features, billing frequency, renewal terms, usage limits, and cancellation instructions will be described in the relevant plan or checkout.", "Customers may request cancellation through the stated procedure. Cancellation and refunds are distinct: cancellation generally affects future service or renewal, while a refund concerns money already paid.", "Any refund, partial refund, credit, or post-cancellation access will be determined by the disclosed plan terms, the applicable agreement, and mandatory legal rights.", "We will not rely on this section to override statutory cancellation, refund, or consumer rights."] },
  { heading: "9. Refunds and Failed Transactions", body: ["Refund eligibility depends on the product or service purchased, the stage of delivery, the published refund policy, the applicable agreement, and relevant law.", "Where a refund is approved, it will ordinarily be processed through the original payment method where supported, subject to provider procedures and legal requirements.", "A payment that failed or was never successfully captured must be investigated separately from a completed payment. Duplicate charges, erroneous debits, and disputed transactions should be reported promptly with the available transaction reference."] },
  { heading: "10. Intellectual Property and Licences", body: ["Unless a written agreement states otherwise, the website's branding, original content, design elements, and underlying materials remain owned by or licensed to their respective rights holders.", "Purchasing a digital product generally grants only the licence or access rights stated in the applicable product terms. A purchase does not automatically transfer copyright, source-code ownership, exclusivity, or intellectual-property rights.", "Ownership and permitted use of custom-developed work, source code, reusable components, third-party libraries, and deliverables should be specified in the project agreement.", "You must not copy, redistribute, resell, reverse engineer, or commercially exploit a product beyond the rights granted to you, except where applicable law permits or the relevant licence authorizes it."] },
  { heading: "11. Acceptable Use", body: ["You must not use our website, products, or services to violate applicable law, infringe intellectual property, distribute malicious code, gain unauthorized access, interfere with system security, or abuse payment or authentication mechanisms.", "You must not use AI agents or automation provided by us to conduct unlawful activities, impersonate others fraudulently, or process information without the required authorization.", "We may investigate suspected misuse and take proportionate action, including restricting access where reasonably necessary and legally permitted."] },
  { heading: "12. Customer Responsibilities", body: ["You are responsible for providing accurate requirements, authorized content, appropriate access permissions, and timely approvals.", "You must have the necessary rights to any data, images, text, code, credentials, or other material you supply.", "Unless otherwise agreed, you remain responsible for the accuracy and lawfulness of your business content, customer communications, and decisions made using the software."] },
  { heading: "13. Third-Party Services", body: ["Products and services may depend on external payment gateways, hosting providers, cloud infrastructure, APIs, AI models, email providers, or other third-party services.", "Those providers may impose their own terms, charges, technical restrictions, and availability limits. We will identify material dependencies where relevant and practicable.", "We are not responsible for an external provider's independent acts or failures to the extent permitted by law. This provision does not exclude any responsibility that applicable law places on us."] },
  { heading: "14. Maintenance, Support, and Availability", body: ["Maintenance, hosting, monitoring, support hours, response targets, and service-level commitments apply only when included in the relevant product or agreement.", "We may perform maintenance, security updates, or emergency changes when reasonably necessary. Where practicable, planned interruptions will be communicated in advance.", "We do not promise that every product will operate continuously, be compatible with every system, or remain free from all defects."] },
  { heading: "15. AI-Related Limitations", body: ["AI-generated outputs may contain inaccuracies, omissions, outdated information, or unsuitable recommendations.", "Unless expressly agreed otherwise, AI outputs should be reviewed before being used for material business, financial, legal, medical, employment, security, or other consequential decisions.", "Customers remain responsible for decisions made using their systems and for applying appropriate human oversight."] },
  { heading: "16. Privacy and Security", body: ["Personal information is handled in accordance with our Privacy Policy and applicable data-protection law.", "We apply reasonable safeguards appropriate to the information and services involved, but no online system can be guaranteed completely secure.", "You must not share credentials or personal information that you are not authorized to disclose."] },
  { heading: "17. Suspension and Termination", body: ["We may restrict or suspend access where reasonably necessary to address security threats, unlawful use, material breach, non-payment, or operational risk, subject to applicable law and contractual obligations.", "Where appropriate and practicable, we will communicate the reason and any steps required to resolve the issue.", "Termination does not remove accrued payment obligations or rights that continue under the applicable agreement or law."] },
  { heading: "18. Warranties and Limitation of Liability", body: ["Services are provided according to their published descriptions and applicable agreements.", "To the extent permitted by law, we do not warrant uninterrupted availability, universal compatibility, or a particular business result.", "Nothing in these terms excludes or restricts liability that cannot lawfully be excluded, including applicable statutory consumer rights. Any other limitation of liability must be interpreted consistently with applicable law and the specific agreement."] },
  { heading: "19. Complaints and Dispute Resolution", body: ["Please contact us first with the order reference, relevant dates, a description of the issue, and any supporting evidence.", "We aim to review complaints fairly and communicate the next steps. Any legally required grievance process, response period, or escalation route will apply as specified by law and our published grievance details.", "Nothing in these terms prevents a customer from exercising a legal right or approaching an appropriate authority or forum."] },
  { heading: "20. Governing Law", body: ["These terms are governed by the laws of India, subject to applicable conflict-of-law principles and mandatory consumer protections.", "Any dispute will be handled by a court or forum with lawful jurisdiction. Nothing in this section removes a customer's statutory rights or imposes an unlawful restriction on access to remedies."] },
  { heading: "21. Changes to These Terms", body: ["We may update these terms to reflect changes in our services, operations, or legal obligations.", "We will publish the revised version with an updated effective date and provide any notice required by law or the applicable agreement. Material changes will not be applied retroactively where prohibited."] },
  { heading: "22. Contact Information", list: ["Business name: [Exact legal/proprietor name]", "Brand: Abhibhideveloper", "Business address: [Complete business or registered address, as applicable]", "Support email: [Monitored support email]", "Grievance contact: [Name or designation and dedicated contact details, where required]", "Effective date: [Insert date]"] },
  { heading: "Legal Details to Complete Before Publishing", body: ["The brand name alone may not identify the legal contracting party. Since Abhibhideveloper is currently a solo, early-stage venture, determine whether you are operating as an individual proprietor, a registered entity, or another legal form, and describe it accurately. Do not copy another startup's legal name, address, GSTIN, registration number, grievance officer, or dispute jurisdiction."] },
]

export const PRIVACY_ADDENDUM: BlockSection[] = [
  { heading: "Privacy Policy — Digital Platform Draft", lead: "Last updated: [Insert publication date]. This draft assumes the website may use accounts, customer dashboards, payments, email verification, support tickets, analytics, and third-party integrations. Publish only the data practices that actually exist, and update this policy when the system changes." },
  { heading: "1. Introduction", body: ["Abhibhideveloper respects the privacy of individuals who visit our website, create accounts, purchase products, request services, or contact us.", "This Privacy Policy explains what personal information we may collect, why we use it, how it may be shared, how it is protected, and how individuals can exercise applicable privacy rights.", "The actual collection and use of information depend on the features you use and the services you purchase."] },
  { heading: "2. Information We May Collect", body: ["Information you provide — This may include your name, email address, telephone number, billing information, business details, project requirements, support messages, and information you voluntarily submit through forms or account settings.", "Account and transaction information — We may process account identifiers, authentication records, order details, subscription status, payment status, invoice information, transaction references, and customer-service history.", "Payment-card details and other sensitive payment credentials should be handled by the authorized payment provider where applicable. We will not claim that we never process payment information unless our actual systems support that statement.", "Technical and usage information — Depending on the website's configuration, we may process IP addresses, browser and device information, log records, security events, session information, and information about how the website is used.", "Project and service information — Information supplied for a project may include business requirements, files, configurations, integration details, and technical information needed to deliver the service.", "Please do not provide passwords, payment credentials, or confidential third-party information unless the relevant process specifically requires it and an appropriate secure method has been provided."] },
  { heading: "3. Why We Use Information", body: ["We may use personal information, as applicable, to: create and administer accounts; respond to enquiries and assess service requirements; process orders, payments, subscriptions, refunds, and billing records; deliver, configure, and maintain purchased products and services; provide customer support and communicate project updates; protect accounts, detect fraud, investigate errors, and secure systems; maintain operational records and meet legal obligations; improve website functionality and understand service usage where permitted; and send promotional communications where legally permitted and subject to applicable preferences or consent requirements.", "We will not describe a purpose as necessary if it is not actually relevant to the processing performed."] },
  { heading: "4. Legal Basis and Consent", body: ["We process information in accordance with applicable law and, where required, based on valid consent or another legally recognized basis.", "Where consent is required, individuals should receive appropriate information and have a usable way to withdraw consent, subject to lawful consequences and any other applicable legal requirements.", "Withdrawing consent does not necessarily invalidate processing that lawfully occurred before withdrawal."] },
  { heading: "5. Payments and Financial Records", body: ["Payments may be processed by third-party payment providers or other authorized channels.", "We may receive transaction identifiers, amounts, payment status, timestamps, and related information needed to verify payments, maintain order records, handle disputes, and provide invoices or receipts.", "We do not treat a payment attempt or an unverified client-side notification as proof that a payment has succeeded.", "Payment providers may separately process information under their own privacy policies and contractual obligations."] },
  { heading: "6. AI Systems and Automated Processing", body: ["Where AI-powered tools are used to deliver a service, information may be processed by the relevant application and its configured model or infrastructure providers.", "The information processed, purposes, retention, and third-party transfers depend on the specific integration.", "We aim to avoid sending unnecessary personal or confidential information to AI providers. Customers should be informed about material processing arrangements relevant to the service they purchase.", "AI-generated content may be inaccurate and should be reviewed where appropriate."] },
  { heading: "7. Sharing and Disclosure", body: ["We may share information with service providers that help us operate the website or deliver services, including hosting providers, authentication services, payment processors, email providers, analytics services, AI infrastructure providers, and technical support tools.", "Information may also be disclosed when required by applicable law, a valid legal process, or necessary to address security incidents, fraud, or the protection of legal rights.", "We do not authorize service providers to use personal information beyond the purposes permitted by applicable arrangements and law.", "We will not claim that personal information is never shared with third parties when external providers are used."] },
  { heading: "8. International Processing", body: ["Some service providers may process information in locations outside India.", "Where international processing occurs, we will handle it in accordance with applicable legal requirements and the arrangements governing the relevant service."] },
  { heading: "9. Data Retention", body: ["We retain information for as long as reasonably necessary for the purposes described in this policy, including account administration, service delivery, dispute resolution, security, and legally required records.", "Different categories of information may have different retention periods. We will delete, erase, or anonymize information when it is no longer required, subject to applicable legal and operational requirements."] },
  { heading: "10. Data Security", body: ["We aim to apply appropriate technical and organizational safeguards, which may include access controls, secure transmission, authentication protections, logging, and restricted access to operational systems.", "The safeguards actually implemented depend on the service and infrastructure. No online system can be guaranteed entirely secure.", "If a personal-data breach occurs, we will take appropriate action and provide notifications where required by applicable law."] },
  { heading: "11. Your Privacy Rights", body: ["Depending on applicable law and the circumstances, you may have rights relating to access to information, correction, updating, erasure, consent withdrawal, grievance redressal, and other available remedies.", "Requests can be sent to the privacy contact listed below. We may need to verify identity and clarify the request before acting.", "These rights remain subject to applicable legal conditions, exceptions, and retention obligations."] },
  { heading: "12. Cookies and Similar Technologies", body: ["The website may use essential cookies or similar technologies for authentication, sessions, security, and other core functionality.", "Analytics, advertising, or other non-essential technologies will be used according to the actual configuration and applicable legal requirements.", "Where required, appropriate consent or preference controls will be provided."] },
  { heading: "13. Children's Information", body: ["Our services are not intentionally directed at children unless a particular product expressly states otherwise. Users must satisfy the applicable eligibility requirements.", "Where information relating to children is processed, we will comply with the legal requirements applicable to that processing."] },
  { heading: "14. External Websites", body: ["Our website may link to third-party websites or services. Their privacy practices are governed by their own policies.", "We encourage users to review the relevant policies before providing information to external providers."] },
  { heading: "15. Changes to This Policy", body: ["We may update this policy to reflect changes in our services, data practices, or legal obligations. The revised version will display an updated effective date.", "Where legally required, we will provide additional notice or obtain consent before implementing a change."] },
  { heading: "16. Contact and Grievances", list: ["Business name: [Exact legal/proprietor name]", "Brand: Abhibhideveloper", "Privacy contact email: [Monitored privacy email]", "Grievance contact: [Name or designation and contact details, where required]", "Business address: [Complete address, as applicable]"] },
  { heading: "Privacy and Indian Law — Important Implementation Point", body: ["India's Digital Personal Data Protection Act, 2023, and the Digital Personal Data Protection Rules, 2025, are relevant to the design of a privacy policy and the handling of personal data. The precise commencement dates and obligations applicable to your business must be checked against official notifications and the current implementation timeline before publication.", "A privacy page alone does not make a website compliant. Your consent flow, account deletion, data access controls, processor arrangements, retention, incident handling, and actual data collection must agree with the policy."] },
]

export const REFUND_ADDENDUM: BlockSection[] = [
  { heading: "Refund, Cancellation, Delivery and Support Policy — Platform Draft", lead: "Last updated: [Insert date]" },
  { heading: "1. Purpose", body: ["This policy explains how Abhibhideveloper handles product delivery, service cancellation, subscription cancellation, refund requests, payment errors, and support requests.", "The applicable product listing, checkout, written quotation, or service agreement may provide additional details. Mandatory legal rights take precedence over any inconsistent term."] },
  { heading: "2. Digital Products", body: ["Delivery may take the form of a download, account access, activation, configuration, or another method specified in the product listing.", "Delivery times may depend on payment verification, technical compatibility, required information, and third-party services.", "If an order has not been delivered as described, please contact support with the order reference and relevant details."] },
  { heading: "3. Custom Development Services", body: ["Custom projects may involve discovery, design, development, testing, deployment, and other agreed milestones.", "Cancellation requests will be assessed against the agreed scope, work completed, committed costs, payment terms, and applicable law.", "Any permitted deduction, refund, or settlement should be based on the contract and actual circumstances, not an undisclosed blanket penalty."] },
  { heading: "4. Subscription Cancellation", body: ["Customers may cancel subscriptions through the method stated in the relevant plan or account interface.", "The cancellation confirmation should explain when cancellation takes effect, whether automatic renewal has been stopped, and how long existing access will continue.", "Unless the plan expressly states otherwise, cancelling a future renewal does not automatically refund a previous billing period.", "This provision does not override mandatory refund or cancellation rights."] },
  { heading: "5. Refund Requests", body: ["To request a refund, contact [support email] with your order ID, transaction reference, purchase date, and a brief explanation.", "We may request reasonable supporting information to verify the transaction and assess the request.", "Refund eligibility depends on the applicable product terms, delivery status, project agreement, payment circumstances, and legal requirements. Where a refund is approved, the processing time depends on the payment provider and banking system.", "We will not use this policy to deny a refund that is legally required."] },
  { heading: "6. Failed, Pending, or Duplicate Payments", body: ["If money appears to have been debited but the order remains unpaid, contact support with the transaction reference and available evidence.", "We will investigate the status using available payment-provider or settlement information.", "Duplicate payments, unsuccessful transactions, and payment reversals will be handled according to the verified transaction outcome and applicable law.", "Please do not send full card numbers, PINs, passwords, or OTPs to support."] },
  { heading: "7. Maintenance and Support", body: ["Support is provided according to the purchased plan or written agreement.", "Support coverage, operating hours, response targets, included fixes, and exclusions should be stated in the relevant plan. New features, unsupported modifications, third-party outages, or additional work may require a separate agreement.", "A response target is not the same as a guaranteed resolution time unless the agreement expressly establishes such a commitment."] },
  { heading: "8. Contact", list: ["Support email: [Monitored support email]", "Grievance contact: [Details, where required]", "Business address: [Address, as applicable]"] },
  { heading: "Recommendation", body: ["Do not publish an unconditional \"all digital products are non-refundable\" statement. Digital purchases, service contracts, failed payments, and subscription renewals can have different legal and contractual consequences. Your policy must account for those differences."] },
]

export const COOKIE_ADDENDUM: BlockSection[] = [
  { heading: "Cookie Policy — Platform Draft", body: ["Abhibhideveloper may use cookies and similar technologies to provide website functionality, maintain secure sessions, remember preferences, understand website usage, and support other disclosed purposes."] },
  { heading: "Essential Cookies", body: ["Essential cookies may be required for authentication, account sessions, security, and core website operations. Disabling them may prevent certain features from functioning correctly."] },
  { heading: "Analytics and Optional Technologies", body: ["Analytics, advertising, or other optional technologies may be used only as configured on the website and in accordance with applicable legal requirements.", "Where required, users will be provided with appropriate information and controls for consent and preferences."] },
  { heading: "Third-Party Technologies", body: ["Some website features may rely on third-party services. Those services may process technical information under their own terms and privacy policies."] },
  { heading: "Managing Preferences", body: ["Where a cookie or preference control is provided, users may use it to manage applicable optional technologies. Browser settings may also allow users to restrict or delete cookies, although doing so can affect functionality."] },
  { heading: "Policy Updates", body: ["This policy may be updated when our website or use of cookies changes."] },
  { heading: "Contact", list: ["[Privacy contact email]"] },
]

export const ACCEPTABLE_USE: BlockSection[] = [
  { heading: "Acceptable Use Policy", body: ["Abhibhideveloper aims to provide digital products and technology services for lawful, authorized, and responsible use."] },
  {
    heading: "Users must not use our website, applications, AI tools, or services to:",
    list: [
      "Access systems, accounts, or data without authorization.",
      "Distribute malware, malicious scripts, or harmful software.",
      "Commit fraud, impersonate others deceptively, or interfere with payment systems.",
      "Infringe copyrights, trademarks, privacy rights, or other legal rights.",
      "Send unlawful spam or abuse authentication, messaging, or automation systems.",
      "Circumvent technical safeguards, access restrictions, or licence limits.",
      "Use AI systems to facilitate unlawful activity or unauthorized disclosure of personal information.",
      "Disrupt the security, availability, or integrity of our systems or those of other users.",
    ],
  },
  { heading: "Responsibilities", body: ["Users must have the necessary rights and permissions for any content, data, accounts, and integrations they provide.", "Where misuse is reasonably suspected, we may investigate and take proportionate action, including restricting access, suspending a service, or reporting conduct where legally appropriate.", "We will handle complaints and account restrictions in accordance with applicable law and relevant contractual obligations."] },
  { heading: "Security Reports", body: ["For security concerns, contact [Security contact email]. Do not include passwords, OTPs, private keys, or other authentication secrets in a report."] },
]
