import React from "react"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service — NexusAI",
  description: "Terms and conditions for using the NexusAI platform, API, and marketplace.",
}

export default function TermsPage() {
  return (
    <div className="bg-[#080808] text-white min-h-screen py-24 px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-black mb-6">Terms of Service</h1>
        <p className="text-zinc-500 mb-12">Last Updated: May 21, 2026</p>

        <div className="prose prose-invert max-w-none text-zinc-300">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the NexusAI platform, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use our services.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            NexusAI provides an orchestration platform, marketplace, and API for deploying autonomous AI agents and SaaS applications (the "Service"). You understand that the Service may include usage limits and billing based on computational resources consumed.
          </p>

          <h2>3. User Conduct & AI Usage Rules</h2>
          <p>
            You agree not to use the Service to:
          </p>
          <ul>
            <li>Generate or distribute malicious code, malware, or spam.</li>
            <li>Bypass or attempt to bypass any rate limits or security mechanisms.</li>
            <li>Generate CSAM, non-consensual deepfakes, or highly deceptive synthetic media.</li>
            <li>Train competing foundational models using data generated by NexusAI.</li>
          </ul>

          <h2>4. Billing, Subscriptions, and Marketplace</h2>
          <p>
            NexusAI uses Stripe as a third-party payment processor. By purchasing a subscription or deploying a paid agent from the Marketplace, you agree to our billing terms. Subscriptions auto-renew unless canceled before the end of the billing cycle. See our <a href="/refund-policy" className="text-purple-400">Refund Policy</a> for more details.
          </p>

          <h2>5. Intellectual Property</h2>
          <p>
            You retain all rights to the data you submit to the Service. NexusAI retains all rights to the platform, underlying software, and UI. We do not claim ownership over the outputs generated by your deployed agents, but you are responsible for ensuring those outputs do not violate third-party IP rights.
          </p>
        </div>
      </div>
    </div>
  )
}
