import * as React from "react"
import { Button, Hr, Link, Section, Text, Heading } from "@react-email/components"
import { EmailShell, baseStyles } from "./_shared"

export interface CommunicationEmailDetail {
  label: string
  value: string
}

interface CommunicationEmailProps {
  preview: string
  title: string
  subtitle?: string
  recipientName?: string
  body: string
  ctaLabel?: string
  ctaUrl?: string
  details?: CommunicationEmailDetail[]
  footerNote?: string
  locale?: string
  unsubscribeUrl?: string
}

export function CommunicationEmail({
  preview,
  title,
  subtitle,
  recipientName = "there",
  body,
  ctaLabel,
  ctaUrl,
  details = [],
  footerNote,
  locale = "en",
  unsubscribeUrl,
}: CommunicationEmailProps) {
  const isRtl = ["ar", "fa", "he", "ur"].includes(locale.toLowerCase())

  return (
    <EmailShell preview={preview} footerNote={footerNote} unsubscribeUrl={unsubscribeUrl} brandTagline="Transactional Communications">
      <Section style={{ textAlign: isRtl ? "right" : "left", marginBottom: 24 }}>
        <Text style={{ ...baseStyles.muted, marginBottom: 8, textTransform: "uppercase", letterSpacing: 1, fontWeight: 700 }}>
          NexusAI Notification
        </Text>
        <Heading as="h1" style={{ ...baseStyles.greeting, fontSize: 26, marginBottom: 8 }}>
          {title}
        </Heading>
        {subtitle && <Text style={{ ...baseStyles.paragraph, color: "#0f172a", opacity: 0.9 }}>{subtitle}</Text>}
      </Section>

      <Section style={{ marginBottom: 20 }}>
        <Text style={baseStyles.paragraph}>Hi {recipientName},</Text>
        <Text style={baseStyles.paragraph}>{body}</Text>
      </Section>

      {details.length > 0 && (
        <Section style={{ ...baseStyles.infoBox, backgroundColor: "#ffffff", border: "1px solid #e2e8f0" }}>
          {details.map((detail) => (
            <Text key={detail.label} style={{ ...baseStyles.infoRow, margin: "8px 0" }}>
              <span style={baseStyles.infoLabel}>{detail.label}</span>
              <span style={{ ...baseStyles.infoValue, textAlign: "right" }}>{detail.value}</span>
            </Text>
          ))}
        </Section>
      )}

      {ctaLabel && ctaUrl && (
        <Section style={{ textAlign: "center", margin: "28px 0" }}>
          <Button href={ctaUrl} style={{ ...baseStyles.button, borderRadius: 12 }}>
            {ctaLabel}
          </Button>
        </Section>
      )}

      <Hr style={baseStyles.divider} />

      <Section>
        <Text style={baseStyles.muted}>
          This message was generated by a backend event and logged to the NexusAI email audit trail.
        </Text>
        <Text style={baseStyles.muted}>
          If you were not expecting this notification, please review your account security and email preferences.
        </Text>
        <Link href={`${process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"}/dashboard/profile`} style={{ color: "#6366f1", textDecoration: "none", fontWeight: 600 }}>
          Manage email preferences
        </Link>
      </Section>
    </EmailShell>
  )
}

export default CommunicationEmail
